# can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac
#
/generator/volume group1Physical
/generator/angdist intoGe
/generator/edist alpha
/generator/particle alpha
/generator/SourceType GeSurface

/run/verbose 0 
/run/initialize
/event/verbose 0
/tracking/verbose 0
/hits/verbose 0
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
#
/run/beamOn 1
/vis/scene/endOfEventAction accumulate 10
/vis/viewer/save
